In [1]:
import numpy as np
from utils.dataloader import *
from utils.coordinate_calibration import PointCloudRegistration
from utils.meshgrid import Meshgrid
from utils.icp import IterativeClosestPoint, Matching

In [2]:
RIGID_BODY_DATA_A = f'./pa345_data/Problem3-BodyA.txt'
RIGID_BODY_DATA_B = f'./pa345_data/Problem3-BodyB.txt'

SURFACE_DATA = f'./pa345_data/Problem3MeshFile.sur'
# SURFACE_DATA = f'./pa345_data/test.sur'

SAMPLE_DATA = f'./pa345_data/PA3-B-Debug-SampleReadingsTest.txt'

rigidbody_dl_A = RigidBodyDataloader.read_file(RIGID_BODY_DATA_A)
rigidbody_dl_B = RigidBodyDataloader.read_file(RIGID_BODY_DATA_B)

# print("rigid body")
# print(rigidbody_dl_A.markers)
# print(rigidbody_dl_A.tip)

surface_dl = Surfaceloader.read_file(SURFACE_DATA)
# print("surface")
# print(surface_dl.N_vertices)
# print(surface_dl.N_triangles)
# print(surface_dl.vertices.shape)
# print(surface_dl.triangles.shape)

sample_dl = SampleReadingsDataloader.read_file(SAMPLE_DATA, delimiter=',', N_A=rigidbody_dl_A.N_markers, N_B=rigidbody_dl_B.N_markers)
# print("sample A", sample_dl.body_A)
# print("sample B", sample_dl.body_B)
# print("dummy", sample_dl.dummy)

### Get F<sub>A, k</sub> and F<sub>B, k</sub>

In [3]:
# TODO get F_A
rigidbody_dl_A_markers = rigidbody_dl_A.markers.reshape(1, -1, 3) # markers of body A in body A coordinates

sample_dl_A = sample_dl.body_A # samples of body A markers in tracker coordinates
num_samples = sample_dl.N_samps

# perform registration for each frame
reg_F_A = PointCloudRegistration()
F_A = []
for i in range(num_samples):
    sample_dl_A_i = sample_dl_A[i].reshape(1, -1, 3)
    F_A_i, err = reg_F_A.register(rigidbody_dl_A_markers, sample_dl_A_i)
    F_A.append(F_A_i)

F_A = np.array(F_A)

# TODO get F_B
ridigbody_dl_B_markers = rigidbody_dl_B.markers.reshape(1, -1, 3) # markers of body B in body B coordinates
sample_dl_B = sample_dl.body_B # samples of body B markers in tracker coordinates

# perform registration for each frame
reg_F_B = PointCloudRegistration()
F_B = []
for i in range(num_samples):
    sample_dl_B_i = sample_dl_B[i].reshape(1, -1, 3)

    F_B_i, err = reg_F_B.register(ridigbody_dl_B_markers, sample_dl_B_i)
    F_B.append(F_B_i)

F_B = np.array(F_B)

Performing 3D point cloud registration...


100ep [00:00<00:00, 746.70it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 491.22it/s, err=0.00266]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 780.43it/s, err=0.00252]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1238.85it/s, err=0.00268]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 748.67it/s, err=0.00261]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 770.28it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 944.54it/s, err=0.00321]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 793.99it/s, err=0.0032]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 816.82it/s, err=0.00324]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 768.17it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 736.51it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1544.83it/s, err=0.00224]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 342.65it/s, err=0.00248]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 631.97it/s, err=0.00225]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 759.19it/s, err=0.00316]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 503.89it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1574.26it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 461.86it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 550.75it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1270.15it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 806.95it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 832.81it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 709.25it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 822.52it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 821.14it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 935.10it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1247.75it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 655.44it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1282.71it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 836.67it/s, err=0.00226]


Done.


### Get d<sub>k

In [4]:
A_tip = rigidbody_dl_A.tip
A_tip = np.append(A_tip, 1) # add 1 for homogenous coordinates
d_k = []

for i in range(num_samples):
    F_A_i = F_A[i] # get F_A for frame i
    F_B_i_inv = np.linalg.inv(F_B[i]) # get F_B inverse for frame i
    # print(A_tip.shape)
    # print(F_A_i.shape)
    # print(F_B_i_inv.shape)

    d_k.append(F_B_i_inv @ F_A_i @ A_tip) # d_k = F_B^-1 * F_A * A_tip

d_k = np.array(d_k)[:,:3]
print(d_k.shape)
print(d_k)

(15, 3)
[[-37.64833678  -9.48581429 -12.76682898]
 [-18.60510135  -9.65676445  -4.29505254]
 [ -2.14008856  -7.91886808  52.44877509]
 [ 17.87241499 -12.57782081   1.66919045]
 [-13.95441346  21.50282627  25.2969365 ]
 [ 28.96426532  19.0550331  -13.73958009]
 [ 24.2614743   22.12267255  -1.99781554]
 [-27.75457871 -23.80052244 -48.36744324]
 [-28.46403537   7.90253067 -35.89238329]
 [-12.65584902   9.56599089  12.90058673]
 [-27.11807733 -28.65576806 -14.35566804]
 [ 37.25503378   5.25779861   4.71164992]
 [ 20.17629056 -14.87243941  -4.87098927]
 [ -4.2582231   12.83878122  54.08074924]
 [ 32.08328176  15.8541175   -2.09464545]]


In [ ]:
# Initialize ICP helper class
# icp = IterativeClosestPoint(Matching.SIMPLE_LINEAR)
# icp = IterativeClosestPoint(Matching.VECTORIZED_LINEAR)
icp = IterativeClosestPoint(Matching.SIMPLE_OCTREE)

# Initialize meshgrid of Triangles
mesh = Meshgrid(surface_dl.vertices, surface_dl.triangles)

# Find closest points and euclidean distances
pt, dist = icp.match(d_k, mesh)

print(np.around(pt, 2))
print(dist)

[[-38.82  -9.64 -11.91]
 [-19.12  -9.7   -2.94]
 [ -1.19  -5.73  52.65]
 [ 17.86 -12.56   1.66]
 [-14.6   22.22  25.28]
 [ 30.52  20.52 -14.02]
 [ 25.46  24.26  -2.07]
 [-27.05 -21.42 -45.7 ]
 [-28.55   8.08 -36.  ]
 [-11.2    8.79  13.3 ]
 [-26.61 -28.39 -13.84]
 [ 39.65   4.99   4.85]
 [ 20.58 -15.33  -4.37]
 [ -4.69  13.35  53.96]
 [ 33.31  16.96  -2.28]]
[1.46267009 1.44865354 2.39889664 0.02119317 0.96874466 2.15581994
 2.4546997  3.64111083 0.22614512 1.69751985 0.77396771 2.41175499
 0.78990696 0.68246187 1.65676735]
