In [1]:
import numpy as np
from utils.dataloader import *
from utils.coordinate_calibration import PointCloudRegistration
from utils.meshgrid import Meshgrid
from utils.icp import IterativeClosestPoint, Matching

In [2]:
RIGID_BODY_DATA_A = f'./pa345_data/Problem3-BodyA.txt'
RIGID_BODY_DATA_B = f'./pa345_data/Problem3-BodyB.txt'

SURFACE_DATA = f'./pa345_data/Problem3MeshFile.sur'

SAMPLE_DATA = f'./pa345_data/PA3-B-Debug-SampleReadingsTest.txt'

rigidbody_dl_A = RigidBodyDataloader.read_file(RIGID_BODY_DATA_A)
rigidbody_dl_B = RigidBodyDataloader.read_file(RIGID_BODY_DATA_B)

# print("rigid body")
# print(rigidbody_dl_A.markers)
# print(rigidbody_dl_A.tip)

surface_dl = Surfaceloader.read_file(SURFACE_DATA)
# print("surface")
# print(surface_dl.N_vertices)
# print(surface_dl.N_triangles)
# print(surface_dl.vertices.shape)
# print(surface_dl.triangles.shape)

sample_dl = SampleReadingsDataloader.read_file(SAMPLE_DATA, delimiter=',', N_A=rigidbody_dl_A.N_markers, N_B=rigidbody_dl_B.N_markers)
# print("sample A", sample_dl.body_A)
# print("sample B", sample_dl.body_B)
# print("dummy", sample_dl.dummy)

(3135, 6)


### Get F<sub>A, k</sub> and F<sub>B, k</sub>

In [3]:
# TODO get F_A
ridigbody_dl_A_markers = rigidbody_dl_A.markers.reshape(1, -1, 3) # markers of body A in body A coordinates
sample_dl_A = sample_dl.body_A # samples of body A markers in tracker coordinates
num_samples = sample_dl.N_samps

# perform registration for each frame
reg_F_A = PointCloudRegistration()
F_A = []
for i in range(num_samples):
    sample_dl_A_i = sample_dl_A[i].reshape(1, -1, 3)
    F_A_i, err = reg_F_A.register(sample_dl_A_i, ridigbody_dl_A_markers)
    F_A.append(F_A_i)

F_A = np.array(F_A)

# TODO get F_B
ridigbody_dl_B_markers = rigidbody_dl_B.markers.reshape(1, -1, 3) # markers of body B in body B coordinates
sample_dl_B = sample_dl.body_B # samples of body B markers in tracker coordinates

# perform registration for each frame
reg_F_B = PointCloudRegistration()
F_B = []
for i in range(num_samples):
    sample_dl_B_i = sample_dl_B[i].reshape(1, -1, 3)

    F_B_i, err = reg_F_B.register(sample_dl_B_i, ridigbody_dl_B_markers)
    F_B.append(F_B_i)

F_B = np.array(F_B)

Performing 3D point cloud registration...


100ep [00:00<00:00, 239.35it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 326.16it/s, err=0.00266]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 465.15it/s, err=0.00252]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1088.33it/s, err=0.00268]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 603.10it/s, err=0.00261]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 886.18it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 433.64it/s, err=0.00321]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 617.61it/s, err=0.0032]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 938.22it/s, err=0.00324]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 620.14it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 431.73it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 728.99it/s, err=0.00224]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 277.94it/s, err=0.00248]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 679.85it/s, err=0.00225]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 365.95it/s, err=0.00316]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 430.16it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 655.43it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 727.93it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1212.83it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 465.28it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 680.67it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 466.09it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 273.01it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1220.39it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1218.07it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 525.56it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1272.54it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 679.72it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 547.33it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 712.92it/s, err=0.00226]

Done.


### Get d<sub>k

In [4]:
A_tip = rigidbody_dl_A.tip
A_tip = np.append(-A_tip, 1) # add 1 for homogenous coordinates
d_k = []

for i in range(num_samples):
    F_A_i = F_A[i] # get F_A for frame i
    F_B_i_inv = np.linalg.inv(F_B[i]) # get F_B inverse for frame i
    # print(A_tip.shape)
    # print(F_A_i.shape)
    # print(F_B_i_inv.shape)

    d_k.append(-(F_B_i_inv @ F_A_i @ A_tip)) # d_k = F_B^-1 * F_A * A_tip

d_k = np.array(d_k)[:,:3]
print(d_k.shape)
print(d_k)

(15, 3)
[[-37.65204421  -9.47970415 -12.76630958]
 [-18.6056764   -9.65348679  -4.29579791]
 [ -2.1389897   -7.92583199  52.44817324]
 [ 17.87355287 -12.5814502    1.66819479]
 [-13.95049431  21.49898865  25.29893437]
 [ 28.96421344  19.05859009 -13.73732709]
 [ 24.25901899  22.12268891  -1.99634218]
 [-27.7570472  -23.79376992 -48.36943629]
 [-28.46196457   7.9039811  -35.8915683 ]
 [-12.6556336    9.56729968  12.90245195]
 [-27.1226449  -28.64986013 -14.35839881]
 [ 37.25419599   5.25703392   4.71129725]
 [ 20.17917028 -14.87216915  -4.87214807]
 [ -4.25773691  12.83287729  54.08251002]
 [ 32.08654313  15.85671585  -2.09160145]]


In [8]:
icp = IterativeClosestPoint(Matching.SIMPLE_LINEAR)

print(surface_dl.triangles)


mesh = Meshgrid(surface_dl.vertices, surface_dl.triangles)


# print(surface_dl.vertices[:20])
# print(mesh.trangles[-2:])
# pt, dist = icp.match(d_k, mesh)

# print(np.around(pt, 2))
# print(dist)

[[3135 3135 3135]
 [  12   19    1]
 [  20   12    1]
 ...
 [1567 1133 1135]
 [1154 1567 1181]
 [1567 1158 1185]]


IndexError: index 3135 is out of bounds for axis 0 with size 1568