In [1]:
import numpy as np
from utils.dataloader import *
from utils.coordinate_calibration import PointCloudRegistration
from utils.meshgrid import Meshgrid
from utils.icp import IterativeClosestPoint, Matching

In [2]:
RIGID_BODY_DATA_A = f'./pa345_data/Problem3-BodyA.txt'
RIGID_BODY_DATA_B = f'./pa345_data/Problem3-BodyB.txt'

SURFACE_DATA = f'./pa345_data/Problem3MeshFile.sur'
# SURFACE_DATA = f'./pa345_data/test.sur'

SAMPLE_DATA = f'./pa345_data/PA3-B-Debug-SampleReadingsTest.txt'

rigidbody_dl_A = RigidBodyDataloader.read_file(RIGID_BODY_DATA_A)
rigidbody_dl_B = RigidBodyDataloader.read_file(RIGID_BODY_DATA_B)

# print("rigid body")
# print(rigidbody_dl_A.markers)
# print(rigidbody_dl_A.tip)

surface_dl = Surfaceloader.read_file(SURFACE_DATA)
# print("surface")
# print(surface_dl.N_vertices)
# print(surface_dl.N_triangles)
# print(surface_dl.vertices.shape)
# print(surface_dl.triangles.shape)

sample_dl = SampleReadingsDataloader.read_file(SAMPLE_DATA, delimiter=',', N_A=rigidbody_dl_A.N_markers, N_B=rigidbody_dl_B.N_markers)
# print("sample A", sample_dl.body_A)
# print("sample B", sample_dl.body_B)
# print("dummy", sample_dl.dummy)

### Get F<sub>A, k</sub> and F<sub>B, k</sub>

In [3]:
# TODO get F_A
rigidbody_dl_A_markers = rigidbody_dl_A.markers.reshape(1, -1, 3) # markers of body A in body A coordinates

sample_dl_A = sample_dl.body_A # samples of body A markers in tracker coordinates
num_samples = sample_dl.N_samps

# perform registration for each frame
reg_F_A = PointCloudRegistration()
F_A = []
for i in range(num_samples):
    sample_dl_A_i = sample_dl_A[i].reshape(1, -1, 3)
    F_A_i, err = reg_F_A.register(rigidbody_dl_A_markers, sample_dl_A_i)
    F_A.append(F_A_i)

F_A = np.array(F_A)

# TODO get F_B
ridigbody_dl_B_markers = rigidbody_dl_B.markers.reshape(1, -1, 3) # markers of body B in body B coordinates
sample_dl_B = sample_dl.body_B # samples of body B markers in tracker coordinates

# perform registration for each frame
reg_F_B = PointCloudRegistration()
F_B = []
for i in range(num_samples):
    sample_dl_B_i = sample_dl_B[i].reshape(1, -1, 3)

    F_B_i, err = reg_F_B.register(ridigbody_dl_B_markers, sample_dl_B_i)
    F_B.append(F_B_i)

F_B = np.array(F_B)

Performing 3D point cloud registration...


100ep [00:00<00:00, 352.90it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 968.54it/s, err=0.00266]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 661.72it/s, err=0.00252]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 782.04it/s, err=0.00268]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 432.45it/s, err=0.00261]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 580.90it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 743.40it/s, err=0.00321]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 573.54it/s, err=0.0032]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 932.31it/s, err=0.00324]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 438.72it/s, err=0.00231]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 303.55it/s, err=0.00281]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 712.99it/s, err=0.00224]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 469.68it/s, err=0.00248]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 816.89it/s, err=0.00225]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1501.17it/s, err=0.00316]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 748.46it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 757.33it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1138.01it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 495.97it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 497.63it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 942.70it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 731.91it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 786.16it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1495.66it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 722.67it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 562.12it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 844.77it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 652.44it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 719.06it/s, err=0.00226]


Done.
Performing 3D point cloud registration...


100ep [00:00<00:00, 1189.77it/s, err=0.00226]

Done.


### Get d<sub>k

In [4]:
A_tip = rigidbody_dl_A.tip
A_tip = np.append(A_tip, 1) # add 1 for homogenous coordinates
d_k = []

for i in range(num_samples):
    F_A_i = F_A[i] # get F_A for frame i
    F_B_i_inv = np.linalg.inv(F_B[i]) # get F_B inverse for frame i
    # print(A_tip.shape)
    # print(F_A_i.shape)
    # print(F_B_i_inv.shape)

    d_k.append(F_B_i_inv @ F_A_i @ A_tip) # d_k = F_B^-1 * F_A * A_tip

d_k = np.array(d_k)[:,:3]
print(d_k.shape)
print(d_k)

(15, 3)
[[-37.64833678  -9.48581429 -12.76682898]
 [-18.60510135  -9.65676445  -4.29505254]
 [ -2.14008856  -7.91886808  52.44877509]
 [ 17.87241499 -12.57782081   1.66919045]
 [-13.95441346  21.50282627  25.2969365 ]
 [ 28.96426532  19.0550331  -13.73958009]
 [ 24.2614743   22.12267255  -1.99781554]
 [-27.75457871 -23.80052244 -48.36744324]
 [-28.46403537   7.90253067 -35.89238329]
 [-12.65584902   9.56599089  12.90058673]
 [-27.11807733 -28.65576806 -14.35566804]
 [ 37.25503378   5.25779861   4.71164992]
 [ 20.17629056 -14.87243941  -4.87098927]
 [ -4.2582231   12.83878122  54.08074924]
 [ 32.08328176  15.8541175   -2.09464545]]


In [8]:
icp = IterativeClosestPoint(Matching.BATCHED_LINEAR)

# print(surface_dl.triangles)
# print(surface_dl.vertices)
print(surface_dl.triangles.shape)


mesh = Meshgrid(surface_dl.vertices, surface_dl.triangles)


# print(surface_dl.vertices[:20])
# print(mesh.trangles[-2:])
pt, dist = icp.match(d_k, mesh)

print(np.around(pt, 2))
print(dist)

(3135, 3)
[[-38.82  -9.64 -11.91]
 [-19.12  -9.7   -2.94]
 [ -1.19  -5.73  52.65]
 [ 17.86 -12.56   1.66]
 [-14.6   22.22  25.28]
 [ 30.81  20.12 -13.97]
 [ 25.46  24.26  -2.07]
 [-27.05 -21.42 -45.7 ]
 [-28.55   8.08 -36.  ]
 [-11.2    8.79  13.3 ]
 [-27.08 -28.51 -14.42]
 [ 39.65   4.99   4.85]
 [ 20.58 -15.33  -4.37]
 [ -4.79  13.09  54.15]
 [ 33.31  16.96  -2.28]]
[1.46267009 1.44865354 2.39889664 0.02119317 0.96874466 2.13998092
 2.4546997  3.64111083 0.22614512 1.69751985 0.16420922 2.41175499
 0.78990696 0.5880446  1.65676735]
